# Generated by Django 2.2.23 on 2021-05-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20190311_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['other_names', 'family_name'], 'permissions': (('approve_person', 'Approve person'), ('merge_person', 'Merge person'))},
        ),
    ]
