# Generated by Django 2.2.23 on 2021-06-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20210522_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name_suffix',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
