# Generated by Django 2.2.23 on 2021-06-25 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_person_name_suffix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativepersonname',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='birth',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='death',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='lifeevent',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='personaddress',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='personassociatedorganisation',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='personassociatedperson',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='servicenumber',
            name='sources',
        ),
    ]
