# Generated by Django 2.2.23 on 2021-06-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20210624_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['family_name', 'other_names'], 'permissions': (('approve_person', 'Approve person'), ('merge_person', 'Merge person'))},
        ),
    ]
