# Generated by Django 2.2.13 on 2021-05-21 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20190311_2222'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='sources',
        ),
        migrations.AddField(
            model_name='source',
            name='creators',
            field=models.ManyToManyField(blank=True, through='sources.SourcePerson', to='people.Person'),
        ),
        migrations.AddField(
            model_name='source',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Repository'),
        ),
        migrations.AddField(
            model_name='sourceperson',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
    ]
